language: c

install:
  - cd scripts
  - bash ./jq.sh
  - bash ./hugo.sh
  - cd ..

before_script:
  - ls -lhAF bin

script:
  - ./bin/hugo

deploy:
  provider: pages
  repo: XhstormR/Blog
  target-branch: master
  local-dir: public
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  on:
    branch: master

cache:
  directories:
    - bin
